name: every_build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
          cache-key: flutter_mac
          cache-path: ${{ runner.tool_cache }}/flutter_mac

      - name: Install dependencies
        run: flutter pub get

      - name: build ipa
        run: flutter build ios --release --no-codesign --dart-define=GOOGLE_CLIENT_ID_IOS=${{ secrets.GOOGLE_CLIENT_ID_IOS }} --dart-define=ICLOUD_CONTAINER_ID=${{ secrets.ICLOUD_CONTAINER_ID }}
      
      - name: mkdir payload and copy .app to Payload/
        run: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
      - name: Compress to zip(ipa)
        run: zip -r app-release.ipa Payload
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios
          path: app-release.ipa
          
  build_android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: false
          cache-key: flutter_linux
          cache-path: ${{ runner.tool_cache }}/flutter_linux

      - name: Install dependencies
        run: flutter pub get

      - name: build apk
        run: flutter build apk --release
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-release.apk

  build_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
          cache-key: flutter_mac
          cache-path: ${{ runner.tool_cache }}/flutter_mac

      - name: Install dependencies
        run: flutter pub get

      - name: build macos
        run: flutter build macos --release --dart-define=GOOGLE_CLIENT_ID_DESKTOP=${{ secrets.GOOGLE_CLIENT_ID_DESKTOP }} --dart-define=GOOGLE_CLIENT_SECRET_DESKTOP=${{ secrets.GOOGLE_CLIENT_SECRET_DESKTOP }} --dart-define=ICLOUD_CONTAINER_ID=${{ secrets.ICLOUD_CONTAINER_ID }}
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: build/macos/Build/Products/Release/Runner.app
  
  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
          cache-key: flutter_windows
          cache-path: ${{ runner.tool_cache }}/flutter_windows

      - name: Install dependencies
        run: flutter pub get

      - name: build windows
        run: flutter build windows --release --dart-define=GOOGLE_CLIENT_ID_DESKTOP=${{ secrets.GOOGLE_CLIENT_ID_DESKTOP }} --dart-define=GOOGLE_CLIENT_SECRET_DESKTOP=${{ secrets.GOOGLE_CLIENT_SECRET_DESKTOP }}
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: build/windows/runner/Release
