name: every_build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
          cache-key: flutter_mac
          cache-path: ${{ runner.tool_cache }}/flutter_mac

      - name: Install dependencies
        run: flutter pub get

      - name: build ipa
        run: flutter build ios --release --no-codesign
      
      - name: mkdir payload and copy .app to Payload/
        run: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
      - name: Compress to zip(ipa)
        run: zip -r app-release.ipa Payload
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios
          path: app-release.ipa
          
  build_android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
          cache-key: flutter_linux
          cache-path: ${{ runner.tool_cache }}/flutter_linux

      - name: Install dependencies
        run: flutter pub get

      - name: build apk
        run: flutter build apk --release
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-release.apk