name: Publish release build

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read
  deployments: write
  id-token: write

jobs:
  build_web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
          cache-key: flutter_linux
          cache-path: ${{ runner.tool_cache }}/flutter_linux

      - name: Install dependencies
        run: |
          flutter pub get
          dart run sqflite_common_ffi_web:setup --force

      - name: build pwa
        run: flutter build web --dart-define=GOOGLE_CLIENT_ID_WEB=${{ secrets.GOOGLE_CLIENT_ID_WEB }} --dart-define=GOOGLE_CLIENT_SECRET_WEB=${{ secrets.GOOGLE_CLIENT_SECRET_WEB }}

      - name: upload to cloudflare pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: leasyprod
          directory: build/web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
